name: Publish

on:
    workflow_dispatch:    
    push:
        branches: 
            - main

env:
    AZURE_WEBAPP_NAME: DE COMPLETAT
    AZURE_WEBAPP_PACKAGE_PATH: DE COMPLETAT

jobs: 
    publish:
        runs-on: ubuntu-latest

        steps:
            - uses: action/checkout@v3
            
            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with: 
                dotnet-version: '8.0.x'

            - name: Restore
              run: dotnet restore "./Lucrare de licenta.sln"

            - name: Build
              run: dotnet build "./Lucrare de licenta.sln" --configuration production --no-restore

            - name: Publish
              run: dotnet publish "./Lucrare de licenta.sln" --configuration production --no-build --output ${( env.AZURE_WEBAPP_PACKAGE_PATH )}

            - name: Deployment
              uses: azure/webapps-deploy@v2
              with:
                app-name: ${( env.AZURE_WEBAPP_NAME )}
                publish-profile: 'DE SETAT CA SECRET!'
                package: ${( env.AZURE_WEBAPP_PACKAGE_PATH )}